### ISSUE TITLE
:farmer: `CmdLine` test regressions on gz-launch5-win

### ISSUE THREAD

**Issue by Crola1702** [gazebosim/gz-launch#202]
## Environment
* OS Version: 
  * Windows
* Source build
  * ign-launch5 branch

## Description
* Expected behavior: No test regressions
* Actual behavior: 6 [CmdLine](https://build.osrfoundation.org/job/ign_launch-ign-5-win/25/testReport/junit/(root)/CmdLine/) test regressions 

## Steps to reproduce
1. Run a job in [ign_launch-win](https://build.osrfoundation.org/job/ign_launch-ign-5-win/25/#showFailuresLink) CI
2. See test regressions fail.

## Output
[CmdLine.HelpVsCompletionFlags](https://build.osrfoundation.org/job/ign_launch-ign-5-win/23/testReport/junit/(root)/CmdLine/HelpVsCompletionFlags/):
<details>

```
C:\Jenkins\workspace\ign_launch-ign-5-win\ws\gz-launch\src\cmd\ign_TEST.cc:136
Expected: (std::string::npos) != (helpOutput.find(flag)), actual: 18446744073709551615 vs 18446744073709551615
Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'
```

</details>

[CmdLine.Ls](https://build.osrfoundation.org/job/ign_launch-ign-5-win/23/testReport/junit/(root)/CmdLine/Ls/):

<details>

```
C:\Jenkins\workspace\ign_launch-ign-5-win\ws\gz-launch\src\cmd\ign_TEST.cc:70
Value of: output.find("CMakeFiles") != std::string::npos
  Actual: false
Expected: true
Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'
```

</details>

[CmdLine.EchoSelf](https://build.osrfoundation.org/job/ign_launch-ign-5-win/23/testReport/junit/(root)/CmdLine/EchoSelf/):

<details>

```
C:\Jenkins\workspace\ign_launch-ign-5-win\ws\gz-launch\src\cmd\ign_TEST.cc:80
Expected equality of these values:
  filePath
    Which is: "C:\\Jenkins\\workspace\\ign_launch-ign-5-win\\ws\\gz-launch\\test\\config\\echo.ign"
  output
    Which is: "Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled\nC:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)\n\tfrom C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'\n\tfrom C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'\n"
With diff:
@@ -1,1 +1,4 @@
-C:\\Jenkins\\workspace\\ign_launch-ign-5-win\\ws\\gz-launch\\test\\config\\echo.ign
+Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
+C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)
+\tfrom C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'
+\tfrom C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'\n

Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'
```

</details>

[CmdLine.HelpSelf](https://build.osrfoundation.org/job/ign_launch-ign-5-win/23/testReport/junit/(root)/CmdLine/HelpSelf/):

<details>

```
C:\Jenkins\workspace\ign_launch-ign-5-win\ws\gz-launch\src\cmd\ign_TEST.cc:88
Expected: (std::string::npos) != (output.find("Introspect Ignition launch")), actual: 18446744073709551615 vs 18446744073709551615
Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'
```

</details>

[CmdLine.EchoErb](https://build.osrfoundation.org/job/ign_launch-ign-5-win/23/testReport/junit/(root)/CmdLine/EchoErb/):

<details>

```
C:\Jenkins\workspace\ign_launch-ign-5-win\ws\gz-launch\src\cmd\ign_TEST.cc:97
Expected equality of these values:
  "erb1234"
  output
    Which is: "Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled\nC:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)\n\tfrom C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'\n\tfrom C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'\n"
With diff:
@@ -1,1 +1,4 @@
-erb1234
+Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
+C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)
+\tfrom C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'
+\tfrom C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'\n

Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'
```

</details>

[CmdLine.EchoBadErb](https://build.osrfoundation.org/job/ign_launch-ign-5-win/23/testReport/junit/(root)/CmdLine/EchoBadErb/):

<details>

```
C:\Jenkins\workspace\ign_launch-ign-5-win\ws\gz-launch\src\cmd\ign_TEST.cc:106
Expected: (std::string::npos) != (output.find("is wrong for erb")), actual: 18446744073709551615 vs 18446744073709551615
Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'
```

</details>

They all have: `ignition-tools-backward.dll not found` in their output

**Comment by Crola1702** [comment]
This happened today in https://build.osrfoundation.org/job/ign_launch-ign-5-win/38/console

**Comment by azeey** [comment]
I was able to resolve the error regarding the invalid path:
```
C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'
	from C:/Jenkins/workspace/ign_launch-ign-5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'
```
with https://github.com/azeey/gz-launch/commit/e6e7805810171f22ce267156f181c07c8396ef08, but now the `UNIT_ign_TEST` times out after 240s. Both the `UNIT_Manager_TEST` and now the `UNIT_ign_TEST` timeout while running `dir` or `ls`, which should return instantly. I'm also not sure if the `UNIT_Manager_TEST` ever passed. The original implementation (#120) indicates 6 failures, which is what we're seeing right now. So I propose we disable both tests on windows.

I'll try to apply https://github.com/azeey/gz-launch/commit/e6e7805810171f22ce267156f181c07c8396ef08 to other gz libraries and hopefully enable `UNIT_ign_TEST/UNIT_gz_TEST`.

**Comment by Crola1702** [comment]
This issue is failing consistently in [gz-launch5-win](https://build.osrfoundation.org/job/gz_launch-ign-launch5-win/)

Reference build: https://build.osrfoundation.org/job/gz_launch-ign-launch5-win/36/

Log output is different this time:
```
C:\J\workspace\gz_launch-ign-launch5-win\ws\gz-launch\src\cmd\ign_TEST.cc:136
Expected: (std::string::npos) != (helpOutput.find(flag)), actual: 18446744073709551615 vs 18446744073709551615
Library error: ignition-tools-backward.dll not found. Improved backtrace generation will be disabled
C:/J/workspace/gz_launch-ign-launch5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in ``': Invalid argument - C:/J/workspace/gz_launch-ign-launch5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/C:/J/workspace/gz_launch-ign-launch5-win/ws/build/ignition-launch5/bin/Release/ign-launch.exe --version (Errno::EINVAL)
	from C:/J/workspace/gz_launch-ign-launch5-win/ws/build/ignition-launch5/test/lib/Release/ruby/ignition/cmdlaunch5.rb:40:in `execute'
	from C:/J/workspace/gz_launch-ign-launch5-win/ws/install/ignition-tools/bin//ign:301:in `<main>'
```

**Comment by Crola1702** [comment]
Closing as this problem hasn't happened since 2024-05-19.
